# Generated by Django 4.2.7 on 2025-11-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alertcontact_website_checkresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
