# Generated by Django 4.2.7 on 2025-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_website_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='website',
            name='is_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='Default Website', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
