# Generated by Django 4.2.7 on 2025-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_website_http_method_website_is_up_website_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresult',
            name='is_healthy',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='response_time',
        ),
        migrations.AddField(
            model_name='checkresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='is_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='response_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
