# Generated by Django 4.2.7 on 2025-11-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_checkresult_is_healthy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
